### ISSUE TITLE
Cannot destructure property 'sapGui' of 't' as it is undefined

### ISSUE THREAD

**Issue by DenisTis** [marcellourbani/abapfs_extensions#5]
Hi Marcell, could you please help? 
I get this message as soon as I try to save my changes (for example class code was changed).
When I create a class it all works fine. 
I use ABAP $TMP package for tests

[Error - 13:33:31] Request textDocument/codeAction failed.
  Message: Request vscabap.readConfig failed with message: Cannot destructure property 'sapGui' of 't' as it is undefined.
  Code: -32603 

Edit: found reason. If in settings.json there is empty line inside vsabap settings, 
then configuration cannot be read.

**Comment by DenisTis** [comment]
Reason was empty line in settings.json:

```
    "abapfs.remote": {
    
    "SYSTEMNAME": {
...
      "language": "EN",
      "allowSelfSigned": true
    }
  },
```

**Comment by marcellourbani** [comment]
Hi Good to read it was a red herring.

**Comment by hismayilov** [comment]
I use VS on MAC with AbapFS. 
I removed space in settings.json, but still I am getting that error.
when i oopen settings.json space is there :) , even I deleted it.

**Comment by marcellourbani** [comment]
Can you please send me the relevant bit of json?
Censuring your password if it's there

**Comment by hismayilov** [comment]
here we go . 
![image](https://user-images.githubusercontent.com/676555/91639699-20015500-ea21-11ea-920f-0ce58fbac81f.png)

**Comment by marcellourbani** [comment]
The remote key shouldn't have spaces in it.
Almost sure that's the issue. 
Will add some validation

**Comment by marcellourbani** [comment]
The url too

**Comment by hismayilov** [comment]
"url": "http://kds.sap.sner.local:8000/"

**Comment by marcellourbani** [comment]
did renaming the configuration work?

**Comment by hismayilov** [comment]
My config name wa "DDD 111"
renamed to "DDD_111",  works fine now :)
